services:
  web:
    image: ${REGISTRY_SERVER}/${WEB_CONTAINER_NAME}:${VERSION_SHORT}
    pull_policy: always
    restart: always
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA: ${GIT_COMMIT_SHA}

  nginx:
    image: ${REGISTRY_SERVER}/${SENTINEL_CONTAINER_NAME}:${VERSION_SHORT}
    pull_policy: always
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /logs/sentinel:/logs/sentinel
    links:
      - web
    depends_on:
      - web
