name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      version: ${{ github.ref_name }}

  deploy-hk:
    uses: ./.github/workflows/deploy-hk.yml
    with:
      version: ${{ github.ref_name }}

  create-release:
    name: Create Release
    runs-on: ubuntu-22.04
    needs:
      - deploy
      - deploy-hk
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.INSCO_RELEASE_TOKEN }}
